version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autobooker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
