name: Fix Dependencies and Deploy

on:
  push:
    branches:
      - main

jobs:
  fix-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Remove old package-lock.json
        run: rm -f package-lock.json
      
      - name: Install dependencies with legacy peer deps
        run: npm install --legacy-peer-deps
      
      - name: Commit new package-lock.json
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add package-lock.json
          git diff --staged --quiet || git commit -m "chore: update package-lock.json with legacy peer deps"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      
      - name: Trigger Netlify deployment
        run: |
          curl -X POST -d {} https://api.netlify.com/build_hooks/YOUR_BUILD_HOOK_ID_HERE
